export const routes = {
    signin: "/signin",
    signup: "/signup",
    home: "/",
    profile: "/profile",
    organizerRegistration: "/profile/organizer-registration",
    createOrganizerRegistration: "/profile/organizer-registration/create",
    organizerRegistrationDetail: "/profile/organizer-registration/:id",
    organizer: "/organizer",
    eventManagement: "/organizer/event",
    createEvent: "/organizer/event/create",
    eventDetail: "/event/:id",
    selectTicket: "/event/:eventId/select-ticket/:eventSessionId",
    payment: "/event/:eventId/select-ticket/:eventSessionId/payment/:bookingId",
    paymentCallback: '/payments/payment-callback',
    myTicket: '/my-tickets',
    order: "/orders",
    orderDetail: "/orders/:id",
    ticketDetail: '/my-tickets/:id',
    eventOverview: "/organizer/event/:id/overview",
    eventAttendee: "/organizer/event/:id/attendee",
    invitationResponse: '/invitation/response'
}